export const labels = [
  { name: 'Node.JS', color: 'green' },
  { name: 'Architecture', color: 'green' },
  { name: 'Full Stack', color: 'green' },
  { name: 'Spring Boot', color: 'green' },
  { name: 'Express.JS', color: 'green' },
  { name: 'LLM', color: 'purple' },
  { name: 'Open AI', color: 'purple' },
  { name: 'Generative AI', color: 'purple' },
  { name: 'NestJS', color: 'red' },
  { name: 'english-speaking', color: 'red' },
  { name: 'german-speaking', color: 'red' },
  { name: 'TypeScript', color: 'red' },
  { name: 'PostgreSQL', color: 'purple' },
  { name: 'Java / Kotlin / JVM', color: 'yellow' },
  { name: 'JavaScript', color: 'red' },
  { name: 'Java', color: 'blue' },
  { name: 'UX', color: 'red' },
  { name: 'Linux', color: 'orange' },
  { name: 'Frontend', color: 'yellow' },
  { name: 'remote-friendly', color: 'yellow' },
  { name: 'Junior friendly', color: 'lime' },
  { name: 'Microfrontends', color: 'red' },
  { name: 'Docker', color: 'orange' },
  { name: 'websockets', color: 'red' },
];
